source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-sitemap'
gem 'octopress', '~> 3.0.0.rc.12'
gem 'rouge'
gem 'kramdown'
gem 'rack-jekyll'
gem 'rake'
gem 'puma'
gem 'foreman'
gem 'thin'
gem 'rack-contrib'